export const blockTitleKeys = {
  LINK: "blockLink",
  FEATURED_LINK: "blockFeaturedLink",
  BUTTON: "blockButton",
  SPACER: "blockSpacer",
  ADULT_LINK: "blockAdultLink",
  TEXT: "blockText",
  HEADING: "blockHeading",
  DIVIDER: "blockDivider",
  IMAGE: "blockImage",
  SOCIALS: "blockSocials",
  HIGHLIGHT: "blockHighlight",
  COUNTDOWN: "blockCountdown",
  VISITOR_COUNTER: "blockVisitorCounter",
  SUPPORT: "blockSupport",
  POLL: "blockPoll",
  DISCORD: "blockDiscord",
  GITHUB: "blockGithub",
  SPOTIFY: "blockSpotify",
  YOUTUBE: "blockYoutube",
  TWITCH: "blockTwitch",
} as const;
