import { CreditCard, Sparkles } from "lucide-react";
import Link from "next/link";
import { getLocale, getTranslations } from "next-intl/server";

import { PageHeader } from "~/components/shell/page-header";
import { Badge } from "~/components/ui/badge";
import { buttonVariants } from "~/components/ui/button";
import { Progress } from "~/components/ui/progress";
import { api } from "~/trpc/server";

type Grants = Awaited<ReturnType<typeof api.subscription.entitlements>>["grants"];
function entitlementLimit(grants: Grants, key: string) { return grants.find((grant) => grant.featureKey === key)?.limit ?? null; }

export default async function BillingPage() {
  const [t, common, locale, subscription, entitlements, usage, checkout] = await Promise.all([getTranslations("billing"), getTranslations("common"), getLocale(), api.subscription.current(), api.subscription.entitlements(), api.subscription.usage(), process.env.NODE_ENV !== "production" ? api.subscription.createDevelopmentCheckout() : null]);
  const usageRows = [{ label: t("profiles"), value: usage.profiles, limit: entitlementLimit(entitlements.grants, "PROFILES") }, { label: t("blocks"), value: usage.blocks, limit: entitlementLimit(entitlements.grants, "BLOCKS") }, { label: t("storage"), value: Math.round(usage.storageMegabytes * 10) / 10, limit: entitlementLimit(entitlements.grants, "FILE_STORAGE"), suffix: " MB" }];
  return <div className="mx-auto w-full max-w-5xl space-y-7"><PageHeader title={t("title")} description={t("subtitle")} /><section className="rounded-lg border border-border bg-surface-raised p-5 shadow-xs"><div className="flex flex-col gap-5 sm:flex-row sm:items-start sm:justify-between"><div className="flex gap-3"><span className="flex size-10 items-center justify-center rounded-md bg-primary/10 text-primary"><Sparkles className="size-4.5" /></span><div><p className="text-xs font-medium text-muted-foreground">{t("currentPlan")}</p><h3 className="mt-1 text-xl font-semibold">OlnkTR {entitlements.plan === "FREE" ? common("free") : common("premium")}</h3><p className="mt-1 text-sm text-muted-foreground">{entitlements.plan === "FREE" ? t("freeDescription") : t("premiumDescription")}</p></div></div><Badge variant={subscription ? "success" : "neutral"}>{subscription ? t("active") : t("inactive")}</Badge></div>{checkout && entitlements.plan === "FREE" ? <div className="mt-5 rounded-md border border-primary/15 bg-primary/5 p-4"><p className="text-sm font-medium">{t("developmentCheckout")}</p><p className="mt-1 text-xs text-muted-foreground">{t("developmentNote")}</p><Link href={checkout.url} className={`${buttonVariants({ size: "sm" })} mt-3`}><CreditCard />{t("upgrade")}</Link></div> : null}{subscription ? <p className="mt-4 text-xs text-muted-foreground">{subscription.currentPeriodEnd ? t("renews", { date: new Intl.DateTimeFormat(locale, { dateStyle: "medium" }).format(subscription.currentPeriodEnd) }) : t("noRenewal")}</p> : null}</section><section className="space-y-4"><h3 className="text-base font-semibold">{t("usage")}</h3><div className="grid gap-3 md:grid-cols-3">{usageRows.map((row) => { const percent = row.limit === null ? 0 : Math.min(100, row.value / row.limit * 100); return <div key={row.label} className="rounded-md border border-border p-4"><div className="flex items-center justify-between gap-3 text-sm"><span className="font-medium">{row.label}</span><span className="text-right text-muted-foreground">{row.limit === null ? t("unlimited") : t("used", { used: `${row.value}${row.suffix ?? ""}`, limit: `${row.limit}${row.suffix ?? ""}` })}</span></div><Progress value={percent} className="mt-3" /></div>; })}</div></section></div>;
}
