import {expect,test} from "@playwright/test";

test("magic link, onboarding, publish, and public profile",async({browser,page,request})=>{
  const stamp=Date.now();const email=`e2e-${stamp}@example.test`;const username=`e2e_${stamp}`;
  await page.goto("/login");await page.getByLabel("Email").fill(email);await page.getByRole("button",{name:"Send magic link"}).click();await expect(page).toHaveURL(/verify-request/);
  let link="";
  for(let attempt=0;attempt<20&&!link;attempt++){const listing=await request.get("http://127.0.0.1:8025/api/v1/messages");const body=await listing.json() as {messages:Array<{ID:string;To:Array<{Address:string}>}>};const hit=body.messages.find(message=>message.To.some(to=>to.Address===email));if(hit){const detail=await (await request.get(`http://127.0.0.1:8025/api/v1/message/${hit.ID}`)).json() as {HTML?:string;Text?:string};link=(detail.HTML??detail.Text??"").match(/https?:\/\/[^\s"<>]+\/api\/auth\/callback\/[^\s"<>]+/)?.[0]?.replaceAll("&amp;","&")??"";}if(!link)await page.waitForTimeout(500);}
  expect(link).not.toBe("");await page.goto(link);const replay=await browser.newPage();await replay.goto(link);expect(replay.url()).toMatch(/error|login/);await replay.close();await page.goto("/onboarding");await page.getByPlaceholder("username").fill(username);await page.getByPlaceholder("Display name").fill("E2E User");await page.getByRole("button",{name:"Create profile"}).click();await expect(page).toHaveURL(/\/dashboard$/);
  await page.goto("/dashboard/content");await page.getByPlaceholder("Link title").fill("Example");await page.getByPlaceholder("https://").fill("https://example.com");await Promise.all([page.waitForResponse(response=>response.request().method()==="POST"&&response.url().includes("/dashboard/content")),page.getByRole("button",{name:"Add link"}).click()]);await Promise.all([page.waitForResponse(response=>response.request().method()==="POST"&&response.url().includes("/dashboard/content")),page.getByRole("button",{name:"Publish current draft"}).click()]);
  await page.goto(`/${username}`);await expect(page.getByRole("heading",{name:"E2E User"})).toBeVisible();await expect(page.getByRole("link",{name:"Example"})).toHaveAttribute("href","https://example.com/");
  await page.goto("/dashboard/billing");await page.getByRole("link",{name:"Activate Premium with development billing"}).click();await expect(page).toHaveURL(/checkout=accepted/);await expect.poll(async()=>{await page.reload();return page.getByText("Plan: PREMIUM").count();},{timeout:10_000}).toBe(1);
  await page.getByRole("button",{name:"Sign out"}).click();await expect(page).toHaveURL(/\/$/);await page.goto("/login");await page.getByLabel("Email").fill(email);await page.getByRole("button",{name:"Send magic link"}).click();await expect(page).toHaveURL(/verify-request/);let secondLink="";for(let attempt=0;attempt<20&&!secondLink;attempt++){const listing=await request.get("http://127.0.0.1:8025/api/v1/messages");const body=await listing.json() as {messages:Array<{ID:string;To:Array<{Address:string}>}>};for(const message of body.messages.filter(item=>item.To.some(to=>to.Address===email))){const detail=await (await request.get(`http://127.0.0.1:8025/api/v1/message/${message.ID}`)).json() as {HTML?:string;Text?:string};const candidate=(detail.HTML??detail.Text??"").match(/https?:\/\/[^\s"<>]+\/api\/auth\/callback\/[^\s"<>]+/)?.[0]?.replaceAll("&amp;","&")??"";if(candidate&&candidate!==link){secondLink=candidate;break;}}if(!secondLink)await page.waitForTimeout(500);}expect(secondLink).not.toBe("");await page.goto(secondLink);await expect(page).toHaveURL(/\/dashboard$/);await page.goto("/dashboard/settings");await page.locator('input[type="file"]').setInputFiles({name:"pixel.png",mimeType:"image/png",buffer:Buffer.from("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9Y9ZQmcAAAAASUVORK5CYII=","base64")});await page.getByRole("button",{name:"Upload"}).click();await expect(page.locator("body")).toContainText('"id"');
});
