import {createWriteStream} from "node:fs";
import type {Readable} from "node:stream";
import {mkdir,rm} from "node:fs/promises";
import path from "node:path";
import {pipeline} from "node:stream/promises";
import {DeleteObjectCommand,GetObjectCommand,PutObjectCommand,S3Client} from "@aws-sdk/client-s3";
import {getSignedUrl} from "@aws-sdk/s3-request-presigner";
import {env} from "~/env";
export interface StorageProvider{putObject(key:string,body:Readable,contentType:string):Promise<void>;deleteObject(key:string):Promise<void>;createSignedUploadUrl(key:string,contentType:string):Promise<string>;createSignedDownloadUrl(key:string):Promise<string>;getPublicUrl(key:string):string}
function safeKey(key:string){if(!/^[a-zA-Z0-9/_-]+\.[a-zA-Z0-9]+$/.test(key)||key.includes(".."))throw new Error("INVALID_OBJECT_KEY");return key;}
class LocalStorageProvider implements StorageProvider{async putObject(key:string,body:Readable){const file=path.resolve(env.LOCAL_STORAGE_PATH,safeKey(key));const root=path.resolve(env.LOCAL_STORAGE_PATH);if(!file.startsWith(`${root}${path.sep}`))throw new Error("INVALID_OBJECT_KEY");await mkdir(path.dirname(file),{recursive:true});await pipeline(body,createWriteStream(file,{flags:"wx"}));}async deleteObject(key:string){await rm(path.resolve(env.LOCAL_STORAGE_PATH,safeKey(key)),{force:true});}async createSignedUploadUrl():Promise<string>{throw new Error("LOCAL_UPLOAD_USES_MULTIPART_ENDPOINT");}async createSignedDownloadUrl(key:string){return this.getPublicUrl(key);}getPublicUrl(key:string){return `${env.STORAGE_PUBLIC_URL}/${safeKey(key)}`;}}
class S3StorageProvider implements StorageProvider{private client=new S3Client({region:env.S3_REGION,endpoint:env.S3_ENDPOINT,forcePathStyle:!!env.S3_ENDPOINT,credentials:env.S3_ACCESS_KEY_ID&&env.S3_SECRET_ACCESS_KEY?{accessKeyId:env.S3_ACCESS_KEY_ID,secretAccessKey:env.S3_SECRET_ACCESS_KEY}:undefined});private bucket(){if(!env.S3_BUCKET)throw new Error("S3_BUCKET_REQUIRED");return env.S3_BUCKET;}async putObject(key:string,body:Readable,contentType:string){await this.client.send(new PutObjectCommand({Bucket:this.bucket(),Key:safeKey(key),Body:body,ContentType:contentType}));}async deleteObject(key:string){await this.client.send(new DeleteObjectCommand({Bucket:this.bucket(),Key:safeKey(key)}));}async createSignedUploadUrl(key:string,contentType:string){return getSignedUrl(this.client,new PutObjectCommand({Bucket:this.bucket(),Key:safeKey(key),ContentType:contentType}),{expiresIn:600});}async createSignedDownloadUrl(key:string){return getSignedUrl(this.client,new GetObjectCommand({Bucket:this.bucket(),Key:safeKey(key)}),{expiresIn:600});}getPublicUrl(key:string){return `${env.S3_ENDPOINT??"https://s3.amazonaws.com"}/${this.bucket()}/${safeKey(key)}`;}}
export const storage:StorageProvider=env.STORAGE_PROVIDER==="s3"?new S3StorageProvider():new LocalStorageProvider();
