import {Readable} from "node:stream";
import {randomUUID,createHash} from "node:crypto";
import {NextResponse} from "next/server";
import {auth} from "~/server/auth";
import {db} from "~/server/db";
import {storage} from "~/server/storage";
import {can} from "~/server/entitlements/service";
import {maximumUploadBytes,validateImageUpload} from "~/server/storage/validation";
export async function POST(request:Request){const session=await auth();if(!session?.user||session.user.status!=="ACTIVE")return new NextResponse(null,{status:401});const form=await request.formData();const file=form.get("file");if(!(file instanceof File)||file.size>maximumUploadBytes)return NextResponse.json({error:"Invalid file"},{status:400});const usage=await db.mediaAsset.aggregate({where:{ownerId:session.user.id,status:{not:"DELETED"}},_sum:{size:true}});const usedMegabytes=Number(usage._sum.size??0)/(1024*1024);const entitlement=await can(session.user.id,"FILE_STORAGE",usedMegabytes);if(!entitlement.allowed||(entitlement.limit!==null&&usedMegabytes+file.size/(1024*1024)>entitlement.limit))return NextResponse.json({error:"Storage limit reached"},{status:403});const bytes=Buffer.from(await file.arrayBuffer());let detected;try{detected=await validateImageUpload(bytes);}catch{return NextResponse.json({error:"Unsupported file"},{status:400});}const key=`users/${session.user.id}/${randomUUID()}.${detected.ext}`;await storage.putObject(key,Readable.from(bytes),detected.mime);try{const asset=await db.mediaAsset.create({data:{ownerId:session.user.id,provider:process.env.STORAGE_PROVIDER==="s3"?"S3":"LOCAL",objectKey:key,originalName:file.name.slice(0,200),mimeType:detected.mime,size:file.size,checksum:createHash("sha256").update(bytes).digest("hex"),status:"READY",private:true}});return NextResponse.json({id:asset.id});}catch(error){await storage.deleteObject(key);throw error;}}
