import {afterAll,describe,expect,it} from "vitest";
import {db} from "~/server/db";
import {completeOnboarding,updateProfile} from "~/server/profile/service";
import {createBlock,updateBlock,updateDraft} from "~/server/page/service";
import {publishPage} from "~/server/publishing/service";
import {getUserEntitlements} from "~/server/entitlements/service";
import {parsePublicationSnapshot} from "~/server/publishing/snapshot";
import {persistBillingWebhook} from "~/server/billing/service";
import {addUtcCalendarMonths,grantManualPremium} from "~/server/billing/manual-subscription";
import {PrismaAdapter} from "@auth/prisma-adapter";
import {requireActiveAccount} from "~/server/security/account";
import {defaultThemeConfig,migrateThemeConfig} from "~/server/publishing/theme-v2";

const integration=process.env.RUN_DB_TESTS==="1"?describe:describe.skip;
integration("PostgreSQL workflows",()=>{
  const userIds:string[]=[];
  afterAll(async()=>{await db.user.deleteMany({where:{id:{in:userIds}}});await db.billingWebhookEvent.deleteMany({where:{provider:"test"}});await db.$disconnect();});
  it("makes concurrent username claims race safe",async()=>{const stamp=Date.now();const users=await Promise.all([db.user.create({data:{email:`race-a-${stamp}@test.local`}}),db.user.create({data:{email:`race-b-${stamp}@test.local`}})]);userIds.push(...users.map(u=>u.id));const results=await Promise.allSettled(users.map(u=>completeOnboarding(u.id,{username:`race_${stamp}`,displayName:"Race"})));expect(results.filter(r=>r.status==="fulfilled")).toHaveLength(1);});
  it("keeps draft edits out of the active snapshot until republished",async()=>{const user=await db.user.create({data:{email:`publish-${Date.now()}@test.local`}});userIds.push(user.id);const profile=await completeOnboarding(user.id,{username:`publish_${Date.now()}`,displayName:"Publisher"});const page=await db.page.findUniqueOrThrow({where:{profileId:profile.id}});const block=await createBlock(user.id,{pageId:page.id,type:"LINK",config:{title:"One",url:"https://example.com/one"}});const first=await publishPage(user.id,page.id);await updateBlock(user.id,{id:block.id,type:"LINK",config:{title:"Two",url:"https://example.com/two"}});const live=await db.pagePublication.findUniqueOrThrow({where:{pageId:page.id},include:{version:true}});expect(parsePublicationSnapshot(live.version.snapshot).blocks[0]?.config).toMatchObject({title:"One"});const second=await publishPage(user.id,page.id);expect(second?.version).toBe((first?.version??0)+1);});
  it("preserves Premium theme intent when a Free publication is denied",async()=>{const stamp=Date.now();const user=await db.user.create({data:{email:`premium-theme-${stamp}@test.local`}});userIds.push(user.id);const profile=await completeOnboarding(user.id,{username:`premium_theme_${stamp}`,displayName:"Theme tester"});const page=await db.page.findUniqueOrThrow({where:{profileId:profile.id}});const premiumTheme={...defaultThemeConfig,background:{type:"VIDEO" as const,assetId:"cm12345678901234567890123",opacity:90,overlay:defaultThemeConfig.background.overlay}};await updateDraft(user.id,{pageId:page.id,title:null,description:null,visibility:"PUBLIC",theme:premiumTheme,seo:{schemaVersion:1,robots:"index,follow"}});await expect(publishPage(user.id,page.id)).rejects.toMatchObject({code:"FEATURE_NOT_AVAILABLE"});const draft=await db.pageDraft.findUniqueOrThrow({where:{pageId:page.id}});expect(migrateThemeConfig(draft.themeConfig).background).toMatchObject({type:"VIDEO",assetId:"cm12345678901234567890123"});});
  it("ignores an expired premium subscription",async()=>{const user=await db.user.create({data:{email:`expired-${Date.now()}@test.local`}});userIds.push(user.id);const premium=await db.plan.findUniqueOrThrow({where:{key:"PREMIUM"}});await db.subscription.create({data:{userId:user.id,planId:premium.id,provider:"test",providerSubscriptionId:`sub-${user.id}`,status:"ACTIVE",currentPeriodEnd:new Date(Date.now()-1000)}});expect((await getUserEntitlements(user.id)).plan).toBe("FREE");});
  it("deduplicates provider webhook event IDs",async()=>{const event={eventId:"same-event",type:"subscription.updated",userId:"user",planKey:"PREMIUM",status:"ACTIVE" as const,providerSubscriptionId:"sub"};await Promise.all([persistBillingWebhook("test",event),persistBillingWebhook("test",event)]);expect(await db.billingWebhookEvent.count({where:{provider:"test",providerEventId:"same-event"}})).toBe(1);});
  it("serializes concurrent manual Premium grants without changing external billing",async()=>{const stamp=Date.now();const [actor,user,premium]=await Promise.all([db.user.create({data:{email:`grant-admin-${stamp}@test.local`,role:"ADMIN"}}),db.user.create({data:{email:`grant-user-${stamp}@test.local`}}),db.plan.findUniqueOrThrow({where:{key:"PREMIUM"}})]);userIds.push(actor.id,user.id);const externalEnd=new Date("2027-01-15T12:00:00.000Z");const external=await db.subscription.create({data:{userId:user.id,planId:premium.id,provider:"test-external",providerSubscriptionId:`external-${stamp}`,status:"ACTIVE",currentPeriodStart:new Date("2026-12-15T12:00:00.000Z"),currentPeriodEnd:externalEnd}});const startedAt=new Date();await Promise.all([grantManualPremium({actorId:actor.id,userId:user.id,months:1,reason:"First bank transfer",confirmation:"CONFIRM"}),grantManualPremium({actorId:actor.id,userId:user.id,months:1,reason:"Second bank transfer",confirmation:"CONFIRM"})]);const manual=await db.subscription.findUniqueOrThrow({where:{provider_providerSubscriptionId:{provider:"manual",providerSubscriptionId:`manual:${user.id}`}}});const expectedEnd=addUtcCalendarMonths(startedAt,2);expect(Math.abs(manual.currentPeriodEnd!.getTime()-expectedEnd.getTime())).toBeLessThan(10_000);expect(await db.subscriptionEvent.count({where:{subscriptionId:manual.id,type:"manual.granted"}})).toBe(2);expect(await db.auditLog.count({where:{actorId:actor.id,targetId:user.id,action:"SUBSCRIPTION_MANUAL_GRANT"}})).toBe(2);expect(await db.subscription.findUniqueOrThrow({where:{id:external.id}})).toMatchObject({status:"ACTIVE",currentPeriodEnd:externalEnd});});
  it("consumes verification tokens once and exposes expiry to Auth.js",async()=>{const adapter=PrismaAdapter(db);const identifier=`expired-${Date.now()}@test.local`;await adapter.createVerificationToken!({identifier,token:"expired-token-hash",expires:new Date(Date.now()-1000)});const token=await adapter.useVerificationToken!({identifier,token:"expired-token-hash"});expect(token?.expires.getTime()).toBeLessThan(Date.now());expect(await adapter.useVerificationToken!({identifier,token:"expired-token-hash"})).toBeNull();});
  it("denies a suspended account at the protected procedure boundary",async()=>{const user=await db.user.create({data:{email:`suspended-${Date.now()}@test.local`,status:"SUSPENDED"}});userIds.push(user.id);await expect(requireActiveAccount(user.id)).rejects.toMatchObject({code:"ACCOUNT_SUSPENDED"});});
  it("prevents cross-owner profile edits and media references",async()=>{const stamp=Date.now();const [owner,other]=await Promise.all([db.user.create({data:{email:`owner-${stamp}@test.local`}}),db.user.create({data:{email:`other-${stamp}@test.local`}})]);userIds.push(owner.id,other.id);const [owned,foreign]=await Promise.all([completeOnboarding(owner.id,{username:`owner_${stamp}`,displayName:"Owner"}),completeOnboarding(other.id,{username:`other_${stamp}`,displayName:"Other"})]);await expect(updateProfile(owner.id,{profileId:foreign.id,displayName:"Stolen"})).rejects.toMatchObject({code:"NOT_FOUND"});const asset=await db.mediaAsset.create({data:{ownerId:other.id,provider:"LOCAL",objectKey:`users/${other.id}/foreign.png`,mimeType:"image/png",size:10,checksum:"foreign",status:"READY",private:true}});const page=await db.page.findUniqueOrThrow({where:{profileId:owned.id}});await expect(createBlock(owner.id,{pageId:page.id,type:"IMAGE",config:{assetId:asset.id,alt:"Foreign"}})).rejects.toMatchObject({code:"VALIDATION_ERROR"});});
});
