import {afterAll,describe,expect,it} from "vitest";
import {db} from "~/server/db";
import {completeOnboarding,updateProfile} from "~/server/profile/service";
import {createBlock,updateBlock} from "~/server/page/service";
import {publishPage} from "~/server/publishing/service";
import {getUserEntitlements} from "~/server/entitlements/service";
import {parsePublicationSnapshot} from "~/server/publishing/snapshot";
import {persistBillingWebhook} from "~/server/billing/service";
import {PrismaAdapter} from "@auth/prisma-adapter";
import {requireActiveAccount} from "~/server/security/account";

const integration=process.env.RUN_DB_TESTS==="1"?describe:describe.skip;
integration("PostgreSQL workflows",()=>{
  const userIds:string[]=[];
  afterAll(async()=>{await db.user.deleteMany({where:{id:{in:userIds}}});await db.billingWebhookEvent.deleteMany({where:{provider:"test"}});await db.$disconnect();});
  it("makes concurrent username claims race safe",async()=>{const stamp=Date.now();const users=await Promise.all([db.user.create({data:{email:`race-a-${stamp}@test.local`}}),db.user.create({data:{email:`race-b-${stamp}@test.local`}})]);userIds.push(...users.map(u=>u.id));const results=await Promise.allSettled(users.map(u=>completeOnboarding(u.id,{username:`race_${stamp}`,displayName:"Race"})));expect(results.filter(r=>r.status==="fulfilled")).toHaveLength(1);});
  it("keeps draft edits out of the active snapshot until republished",async()=>{const user=await db.user.create({data:{email:`publish-${Date.now()}@test.local`}});userIds.push(user.id);const profile=await completeOnboarding(user.id,{username:`publish_${Date.now()}`,displayName:"Publisher"});const page=await db.page.findUniqueOrThrow({where:{profileId:profile.id}});const block=await createBlock(user.id,{pageId:page.id,type:"LINK",config:{title:"One",url:"https://example.com/one"}});const first=await publishPage(user.id,page.id);await updateBlock(user.id,{id:block.id,type:"LINK",config:{title:"Two",url:"https://example.com/two"}});const live=await db.pagePublication.findUniqueOrThrow({where:{pageId:page.id},include:{version:true}});expect(parsePublicationSnapshot(live.version.snapshot).blocks[0]?.config).toMatchObject({title:"One"});const second=await publishPage(user.id,page.id);expect(second?.version).toBe((first?.version??0)+1);});
  it("ignores an expired premium subscription",async()=>{const user=await db.user.create({data:{email:`expired-${Date.now()}@test.local`}});userIds.push(user.id);const premium=await db.plan.findUniqueOrThrow({where:{key:"PREMIUM"}});await db.subscription.create({data:{userId:user.id,planId:premium.id,provider:"test",providerSubscriptionId:`sub-${user.id}`,status:"ACTIVE",currentPeriodEnd:new Date(Date.now()-1000)}});expect((await getUserEntitlements(user.id)).plan).toBe("FREE");});
  it("deduplicates provider webhook event IDs",async()=>{const event={eventId:"same-event",type:"subscription.updated",userId:"user",planKey:"PREMIUM",status:"ACTIVE" as const,providerSubscriptionId:"sub"};await Promise.all([persistBillingWebhook("test",event),persistBillingWebhook("test",event)]);expect(await db.billingWebhookEvent.count({where:{provider:"test",providerEventId:"same-event"}})).toBe(1);});
  it("consumes verification tokens once and exposes expiry to Auth.js",async()=>{const adapter=PrismaAdapter(db);const identifier=`expired-${Date.now()}@test.local`;await adapter.createVerificationToken!({identifier,token:"expired-token-hash",expires:new Date(Date.now()-1000)});const token=await adapter.useVerificationToken!({identifier,token:"expired-token-hash"});expect(token?.expires.getTime()).toBeLessThan(Date.now());expect(await adapter.useVerificationToken!({identifier,token:"expired-token-hash"})).toBeNull();});
  it("denies a suspended account at the protected procedure boundary",async()=>{const user=await db.user.create({data:{email:`suspended-${Date.now()}@test.local`,status:"SUSPENDED"}});userIds.push(user.id);await expect(requireActiveAccount(user.id)).rejects.toMatchObject({code:"ACCOUNT_SUSPENDED"});});
  it("prevents cross-owner profile edits and media references",async()=>{const stamp=Date.now();const [owner,other]=await Promise.all([db.user.create({data:{email:`owner-${stamp}@test.local`}}),db.user.create({data:{email:`other-${stamp}@test.local`}})]);userIds.push(owner.id,other.id);const [owned,foreign]=await Promise.all([completeOnboarding(owner.id,{username:`owner_${stamp}`,displayName:"Owner"}),completeOnboarding(other.id,{username:`other_${stamp}`,displayName:"Other"})]);await expect(updateProfile(owner.id,{profileId:foreign.id,displayName:"Stolen"})).rejects.toMatchObject({code:"NOT_FOUND"});const asset=await db.mediaAsset.create({data:{ownerId:other.id,provider:"LOCAL",objectKey:`users/${other.id}/foreign.png`,mimeType:"image/png",size:10,checksum:"foreign",status:"READY",private:true}});const page=await db.page.findUniqueOrThrow({where:{profileId:owned.id}});await expect(createBlock(owner.id,{pageId:page.id,type:"IMAGE",config:{assetId:asset.id,alt:"Foreign"}})).rejects.toMatchObject({code:"VALIDATION_ERROR"});});
});
