import {z} from "zod";
import {adminProcedure,createTRPCRouter} from "../trpc";
import {AppError} from "~/server/errors";
import {hasPermission} from "~/server/security/authorization";
import {usernameFormatSchema} from "~/server/profile/username";

const confirmation=z.literal("CONFIRM");
function requirePermission(role:"USER"|"MODERATOR"|"ADMIN"|"SUPER_ADMIN",permission:Parameters<typeof hasPermission>[1]){if(!hasPermission(role,permission))throw new AppError("FORBIDDEN","Permission denied");}

export const adminRouter=createTRPCRouter({
  users:adminProcedure.input(z.object({query:z.string().max(100).default("")})).query(({ctx,input})=>ctx.db.user.findMany({where:{OR:[{email:{contains:input.query,mode:"insensitive"}},{name:{contains:input.query,mode:"insensitive"}}]},take:50,include:{profiles:true,subscriptions:{include:{plan:true}}}})),
  setSuspended:adminProcedure.input(z.object({userId:z.string().cuid(),suspended:z.boolean(),confirmation})).mutation(({ctx,input})=>{requirePermission(ctx.session.user.role,"USER_SUSPEND");if(input.userId===ctx.session.user.id)throw new AppError("CONFLICT","You cannot suspend your own account");return ctx.db.$transaction(async tx=>{const user=await tx.user.update({where:{id:input.userId},data:{status:input.suspended?"SUSPENDED":"ACTIVE"}});if(input.suspended)await tx.session.updateMany({where:{userId:input.userId},data:{expires:new Date(0),revokedAt:new Date()}});await tx.auditLog.create({data:{actorId:ctx.session.user.id,actorType:"ADMIN",action:input.suspended?"USER_SUSPENDED":"USER_UNSUSPENDED",targetType:"User",targetId:input.userId}});return user;});}),
  setProfileHidden:adminProcedure.input(z.object({profileId:z.string().cuid(),hidden:z.boolean(),confirmation})).mutation(({ctx,input})=>{requirePermission(ctx.session.user.role,"PROFILE_MODERATE");return ctx.db.$transaction(async tx=>{const profile=await tx.profile.update({where:{id:input.profileId},data:{status:input.hidden?"HIDDEN":"ACTIVE"}});await tx.auditLog.create({data:{actorId:ctx.session.user.id,actorType:"ADMIN",action:input.hidden?"PROFILE_HIDDEN":"PROFILE_UNHIDDEN",targetType:"Profile",targetId:profile.id}});return profile;});}),
  flags:adminProcedure.query(({ctx})=>ctx.db.featureFlag.findMany({orderBy:{key:"asc"}})),
  setFlag:adminProcedure.input(z.object({key:z.string().min(2).max(80),enabled:z.boolean()})).mutation(({ctx,input})=>{requirePermission(ctx.session.user.role,"FLAG_MANAGE");return ctx.db.$transaction(async tx=>{const flag=await tx.featureFlag.upsert({where:{key:input.key},create:input,update:{enabled:input.enabled}});await tx.auditLog.create({data:{actorId:ctx.session.user.id,actorType:"ADMIN",action:"FEATURE_FLAG_UPDATED",targetType:"FeatureFlag",targetId:flag.id,metadata:{enabled:input.enabled}}});return flag;});}),
  reservedUsernames:adminProcedure.query(({ctx})=>ctx.db.reservedUsername.findMany({orderBy:{username:"asc"}})),
  reserveUsername:adminProcedure.input(z.object({username:usernameFormatSchema,reason:z.string().min(2).max(200)})).mutation(({ctx,input})=>{requirePermission(ctx.session.user.role,"FLAG_MANAGE");return ctx.db.$transaction(async tx=>{const value=await tx.reservedUsername.upsert({where:{username:input.username},create:{...input,createdBy:ctx.session.user.id},update:{reason:input.reason}});await tx.auditLog.create({data:{actorId:ctx.session.user.id,actorType:"ADMIN",action:"USERNAME_RESERVED",targetType:"ReservedUsername",targetId:value.username}});return value;});}),
  releaseUsername:adminProcedure.input(z.object({username:usernameFormatSchema,confirmation})).mutation(({ctx,input})=>{requirePermission(ctx.session.user.role,"FLAG_MANAGE");return ctx.db.$transaction(async tx=>{const result=await tx.reservedUsername.deleteMany({where:{username:input.username}});await tx.auditLog.create({data:{actorId:ctx.session.user.id,actorType:"ADMIN",action:"USERNAME_RELEASED",targetType:"ReservedUsername",targetId:input.username}});return result;});}),
  catalog:adminProcedure.query(({ctx})=>ctx.db.plan.findMany({orderBy:{sortOrder:"asc"},include:{entitlements:{include:{feature:true}}}})),
  setPlanEntitlement:adminProcedure.input(z.object({planKey:z.string(),featureKey:z.string(),enabled:z.boolean(),limit:z.number().int().nonnegative().nullable(),confirmation})).mutation(({ctx,input})=>{requirePermission(ctx.session.user.role,"PLAN_MANAGE");return ctx.db.$transaction(async tx=>{const [plan,feature]=await Promise.all([tx.plan.findUniqueOrThrow({where:{key:input.planKey}}),tx.feature.findUniqueOrThrow({where:{key:input.featureKey}})]);const entitlement=await tx.planEntitlement.upsert({where:{planId_featureId:{planId:plan.id,featureId:feature.id}},create:{planId:plan.id,featureId:feature.id,enabled:input.enabled,limit:input.limit},update:{enabled:input.enabled,limit:input.limit}});await tx.auditLog.create({data:{actorId:ctx.session.user.id,actorType:"ADMIN",action:"PLAN_ENTITLEMENT_UPDATED",targetType:"PlanEntitlement",targetId:entitlement.id,metadata:{planKey:input.planKey,featureKey:input.featureKey,enabled:input.enabled,limit:input.limit}}});return entitlement;});}),
  jobs:adminProcedure.query(({ctx})=>ctx.db.jobFailure.findMany({where:{resolvedAt:null},take:100,orderBy:{createdAt:"desc"}})),
  audit:adminProcedure.query(({ctx})=>{requirePermission(ctx.session.user.role,"AUDIT_READ");return ctx.db.auditLog.findMany({take:100,orderBy:{createdAt:"desc"}});})
});
