import {createHash} from "node:crypto";
import {z} from "zod";
import {createTRPCRouter,protectedProcedure,publicProcedure} from "../trpc";
import {AppError} from "~/server/errors";
import {hasPermission} from "~/server/security/authorization";
import {rateLimit} from "~/server/security/rate-limit";
import {env} from "~/env";

export const moderationRouter=createTRPCRouter({
  report:publicProcedure.input(z.object({profileId:z.string().cuid(),blockId:z.string().cuid().optional(),reason:z.enum(["SPAM","PHISHING","MALWARE","IMPERSONATION","ABUSE","OTHER"]),details:z.string().max(1000).optional()})).mutation(async({ctx,input})=>{const ip=ctx.headers.get("x-forwarded-for")?.split(",")[0]?.trim()??"unknown";if(!(await rateLimit("report",ip,5,3600)).allowed)throw new AppError("RATE_LIMITED","Too many reports");if(input.blockId&&!await ctx.db.block.findFirst({where:{id:input.blockId,page:{profileId:input.profileId}}}))throw new AppError("VALIDATION_ERROR","Block does not belong to profile");return ctx.db.report.create({data:{...input,reporterHash:createHash("sha256").update(`${env.ANALYTICS_SALT}:report:${ip}`).digest("hex")},select:{id:true,status:true}});}),
  cases:protectedProcedure.query(({ctx})=>{if(!hasPermission(ctx.session.user.role,"REPORT_REVIEW"))throw new AppError("FORBIDDEN","Permission denied");return ctx.db.moderationCase.findMany({take:100,orderBy:{createdAt:"desc"},include:{report:true,profile:true,actions:true}});}),
  openCase:protectedProcedure.input(z.object({reportId:z.string().cuid()})).mutation(({ctx,input})=>{if(!hasPermission(ctx.session.user.role,"REPORT_REVIEW"))throw new AppError("FORBIDDEN","Permission denied");return ctx.db.$transaction(async tx=>{const report=await tx.report.findUniqueOrThrow({where:{id:input.reportId}});const item=await tx.moderationCase.upsert({where:{reportId:report.id},create:{reportId:report.id,profileId:report.profileId,assignedToId:ctx.session.user.id,status:"REVIEWING"},update:{assignedToId:ctx.session.user.id,status:"REVIEWING"}});await tx.report.update({where:{id:report.id},data:{status:"REVIEWING"}});await tx.auditLog.create({data:{actorId:ctx.session.user.id,actorType:"ADMIN",action:"MODERATION_CASE_OPENED",targetType:"ModerationCase",targetId:item.id}});return item;});}),
  act:protectedProcedure.input(z.object({caseId:z.string().cuid(),type:z.enum(["HIDE_PROFILE","RESTORE_PROFILE","RESOLVE","DISMISS"]),reason:z.string().min(3).max(500)})).mutation(({ctx,input})=>{if(!hasPermission(ctx.session.user.role,"PROFILE_MODERATE"))throw new AppError("FORBIDDEN","Permission denied");return ctx.db.$transaction(async tx=>{const item=await tx.moderationCase.findUniqueOrThrow({where:{id:input.caseId}});if(input.type==="HIDE_PROFILE"||input.type==="RESTORE_PROFILE")await tx.profile.update({where:{id:item.profileId},data:{status:input.type==="HIDE_PROFILE"?"MODERATION_HOLD":"ACTIVE"}});const status=input.type==="DISMISS"?"DISMISSED":input.type==="RESOLVE"?"RESOLVED":item.status;await tx.moderationCase.update({where:{id:item.id},data:{status}});await tx.report.update({where:{id:item.reportId},data:{status}});const action=await tx.moderationAction.create({data:{caseId:item.id,actorId:ctx.session.user.id,type:input.type,reason:input.reason}});await tx.auditLog.create({data:{actorId:ctx.session.user.id,actorType:"ADMIN",action:`MODERATION_${input.type}`,targetType:"Profile",targetId:item.profileId}});return action;});})
});
